/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing AdGroupKeywordTargetRankRecommendationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdGroupKeywordTargetRankRecommendationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdGroupKeywordTargetRankRecommendationRequest
        //private AdGroupKeywordTargetRankRecommendationRequest instance;

        public AdGroupKeywordTargetRankRecommendationRequestTests()
        {
            // TODO uncomment below to create an instance of AdGroupKeywordTargetRankRecommendationRequest
            //instance = new AdGroupKeywordTargetRankRecommendationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdGroupKeywordTargetRankRecommendationRequest
        /// </summary>
        [Fact]
        public void AdGroupKeywordTargetRankRecommendationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdGroupKeywordTargetRankRecommendationRequest
            //Assert.IsType<AdGroupKeywordTargetRankRecommendationRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            // TODO unit test for the property 'CampaignId'
        }
        /// <summary>
        /// Test the property 'RecommendationType'
        /// </summary>
        [Fact]
        public void RecommendationTypeTest()
        {
            // TODO unit test for the property 'RecommendationType'
        }
        /// <summary>
        /// Test the property 'AdGroupId'
        /// </summary>
        [Fact]
        public void AdGroupIdTest()
        {
            // TODO unit test for the property 'AdGroupId'
        }
        /// <summary>
        /// Test the property 'MaxRecommendations'
        /// </summary>
        [Fact]
        public void MaxRecommendationsTest()
        {
            // TODO unit test for the property 'MaxRecommendations'
        }
        /// <summary>
        /// Test the property 'SortDimension'
        /// </summary>
        [Fact]
        public void SortDimensionTest()
        {
            // TODO unit test for the property 'SortDimension'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

    }

}
