/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing Adjustment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdjustmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Adjustment
        //private Adjustment instance;

        public AdjustmentTests()
        {
            // TODO uncomment below to create an instance of Adjustment
            //instance = new Adjustment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Adjustment
        /// </summary>
        [Fact]
        public void AdjustmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Adjustment
            //Assert.IsType<Adjustment>(instance);
        }


        /// <summary>
        /// Test the property 'PlacementAdjustment'
        /// </summary>
        [Fact]
        public void PlacementAdjustmentTest()
        {
            // TODO unit test for the property 'PlacementAdjustment'
        }

    }

}
