/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing AsinsThemeBasedBidRecommendationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AsinsThemeBasedBidRecommendationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AsinsThemeBasedBidRecommendationRequest
        //private AsinsThemeBasedBidRecommendationRequest instance;

        public AsinsThemeBasedBidRecommendationRequestTests()
        {
            // TODO uncomment below to create an instance of AsinsThemeBasedBidRecommendationRequest
            //instance = new AsinsThemeBasedBidRecommendationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AsinsThemeBasedBidRecommendationRequest
        /// </summary>
        [Fact]
        public void AsinsThemeBasedBidRecommendationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AsinsThemeBasedBidRecommendationRequest
            //Assert.IsType<AsinsThemeBasedBidRecommendationRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Asins'
        /// </summary>
        [Fact]
        public void AsinsTest()
        {
            // TODO unit test for the property 'Asins'
        }
        /// <summary>
        /// Test the property 'TargetingExpressions'
        /// </summary>
        [Fact]
        public void TargetingExpressionsTest()
        {
            // TODO unit test for the property 'TargetingExpressions'
        }
        /// <summary>
        /// Test the property 'Bidding'
        /// </summary>
        [Fact]
        public void BiddingTest()
        {
            // TODO unit test for the property 'Bidding'
        }
        /// <summary>
        /// Test the property 'RecommendationType'
        /// </summary>
        [Fact]
        public void RecommendationTypeTest()
        {
            // TODO unit test for the property 'RecommendationType'
        }

    }

}
