/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing BidValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BidValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BidValue
        //private BidValue instance;

        public BidValueTests()
        {
            // TODO uncomment below to create an instance of BidValue
            //instance = new BidValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BidValue
        /// </summary>
        [Fact]
        public void BidValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" BidValue
            //Assert.IsType<BidValue>(instance);
        }


        /// <summary>
        /// Test the property 'SuggestedBid'
        /// </summary>
        [Fact]
        public void SuggestedBidTest()
        {
            // TODO unit test for the property 'SuggestedBid'
        }

    }

}
