/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing BudgetUsagePortfolio
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BudgetUsagePortfolioTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BudgetUsagePortfolio
        //private BudgetUsagePortfolio instance;

        public BudgetUsagePortfolioTests()
        {
            // TODO uncomment below to create an instance of BudgetUsagePortfolio
            //instance = new BudgetUsagePortfolio();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BudgetUsagePortfolio
        /// </summary>
        [Fact]
        public void BudgetUsagePortfolioInstanceTest()
        {
            // TODO uncomment below to test "IsType" BudgetUsagePortfolio
            //Assert.IsType<BudgetUsagePortfolio>(instance);
        }


        /// <summary>
        /// Test the property 'BudgetUsagePercent'
        /// </summary>
        [Fact]
        public void BudgetUsagePercentTest()
        {
            // TODO unit test for the property 'BudgetUsagePercent'
        }
        /// <summary>
        /// Test the property 'PortfolioId'
        /// </summary>
        [Fact]
        public void PortfolioIdTest()
        {
            // TODO unit test for the property 'PortfolioId'
        }
        /// <summary>
        /// Test the property 'UsageUpdatedTimestamp'
        /// </summary>
        [Fact]
        public void UsageUpdatedTimestampTest()
        {
            // TODO unit test for the property 'UsageUpdatedTimestamp'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Budget'
        /// </summary>
        [Fact]
        public void BudgetTest()
        {
            // TODO unit test for the property 'Budget'
        }

    }

}
