/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing BudgetUsagePortfolioBatchError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BudgetUsagePortfolioBatchErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BudgetUsagePortfolioBatchError
        //private BudgetUsagePortfolioBatchError instance;

        public BudgetUsagePortfolioBatchErrorTests()
        {
            // TODO uncomment below to create an instance of BudgetUsagePortfolioBatchError
            //instance = new BudgetUsagePortfolioBatchError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BudgetUsagePortfolioBatchError
        /// </summary>
        [Fact]
        public void BudgetUsagePortfolioBatchErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" BudgetUsagePortfolioBatchError
            //Assert.IsType<BudgetUsagePortfolioBatchError>(instance);
        }


        /// <summary>
        /// Test the property 'PortfolioId'
        /// </summary>
        [Fact]
        public void PortfolioIdTest()
        {
            // TODO unit test for the property 'PortfolioId'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

    }

}
