/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing DeleteSPCampaignOptimizationRuleResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteSPCampaignOptimizationRuleResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteSPCampaignOptimizationRuleResponse
        //private DeleteSPCampaignOptimizationRuleResponse instance;

        public DeleteSPCampaignOptimizationRuleResponseTests()
        {
            // TODO uncomment below to create an instance of DeleteSPCampaignOptimizationRuleResponse
            //instance = new DeleteSPCampaignOptimizationRuleResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteSPCampaignOptimizationRuleResponse
        /// </summary>
        [Fact]
        public void DeleteSPCampaignOptimizationRuleResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeleteSPCampaignOptimizationRuleResponse
            //Assert.IsType<DeleteSPCampaignOptimizationRuleResponse>(instance);
        }


        /// <summary>
        /// Test the property 'CampaignOptimizationId'
        /// </summary>
        [Fact]
        public void CampaignOptimizationIdTest()
        {
            // TODO unit test for the property 'CampaignOptimizationId'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

    }

}
