/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing InitialBudgetRecommendationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InitialBudgetRecommendationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InitialBudgetRecommendationResponse
        //private InitialBudgetRecommendationResponse instance;

        public InitialBudgetRecommendationResponseTests()
        {
            // TODO uncomment below to create an instance of InitialBudgetRecommendationResponse
            //instance = new InitialBudgetRecommendationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InitialBudgetRecommendationResponse
        /// </summary>
        [Fact]
        public void InitialBudgetRecommendationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" InitialBudgetRecommendationResponse
            //Assert.IsType<InitialBudgetRecommendationResponse>(instance);
        }


        /// <summary>
        /// Test the property 'SpecialEvents'
        /// </summary>
        [Fact]
        public void SpecialEventsTest()
        {
            // TODO unit test for the property 'SpecialEvents'
        }
        /// <summary>
        /// Test the property 'DailyBudget'
        /// </summary>
        [Fact]
        public void DailyBudgetTest()
        {
            // TODO unit test for the property 'DailyBudget'
        }
        /// <summary>
        /// Test the property 'RecommendationId'
        /// </summary>
        [Fact]
        public void RecommendationIdTest()
        {
            // TODO unit test for the property 'RecommendationId'
        }
        /// <summary>
        /// Test the property 'Benchmark'
        /// </summary>
        [Fact]
        public void BenchmarkTest()
        {
            // TODO unit test for the property 'Benchmark'
        }

    }

}
