/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing ProductRecommendationsByASIN
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductRecommendationsByASINTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductRecommendationsByASIN
        //private ProductRecommendationsByASIN instance;

        public ProductRecommendationsByASINTests()
        {
            // TODO uncomment below to create an instance of ProductRecommendationsByASIN
            //instance = new ProductRecommendationsByASIN();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductRecommendationsByASIN
        /// </summary>
        [Fact]
        public void ProductRecommendationsByASINInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductRecommendationsByASIN
            //Assert.IsType<ProductRecommendationsByASIN>(instance);
        }


        /// <summary>
        /// Test the property 'NextCursor'
        /// </summary>
        [Fact]
        public void NextCursorTest()
        {
            // TODO unit test for the property 'NextCursor'
        }
        /// <summary>
        /// Test the property 'PreviousCursor'
        /// </summary>
        [Fact]
        public void PreviousCursorTest()
        {
            // TODO unit test for the property 'PreviousCursor'
        }
        /// <summary>
        /// Test the property 'Recommendations'
        /// </summary>
        [Fact]
        public void RecommendationsTest()
        {
            // TODO unit test for the property 'Recommendations'
        }

    }

}
