/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing RecommendationOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecommendationOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecommendationOptions
        //private RecommendationOptions instance;

        public RecommendationOptionsTests()
        {
            // TODO uncomment below to create an instance of RecommendationOptions
            //instance = new RecommendationOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecommendationOptions
        /// </summary>
        [Fact]
        public void RecommendationOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecommendationOptions
            //Assert.IsType<RecommendationOptions>(instance);
        }


        /// <summary>
        /// Test the property 'MaxRecommendations'
        /// </summary>
        [Fact]
        public void MaxRecommendationsTest()
        {
            // TODO unit test for the property 'MaxRecommendations'
        }
        /// <summary>
        /// Test the property 'SortDimension'
        /// </summary>
        [Fact]
        public void SortDimensionTest()
        {
            // TODO unit test for the property 'SortDimension'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

    }

}
