/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SBListAssociatedBudgetRulesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SBListAssociatedBudgetRulesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SBListAssociatedBudgetRulesResponse
        //private SBListAssociatedBudgetRulesResponse instance;

        public SBListAssociatedBudgetRulesResponseTests()
        {
            // TODO uncomment below to create an instance of SBListAssociatedBudgetRulesResponse
            //instance = new SBListAssociatedBudgetRulesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SBListAssociatedBudgetRulesResponse
        /// </summary>
        [Fact]
        public void SBListAssociatedBudgetRulesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SBListAssociatedBudgetRulesResponse
            //Assert.IsType<SBListAssociatedBudgetRulesResponse>(instance);
        }


        /// <summary>
        /// Test the property 'AssociatedRules'
        /// </summary>
        [Fact]
        public void AssociatedRulesTest()
        {
            // TODO unit test for the property 'AssociatedRules'
        }

    }

}
