/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SBRuleBasedBudget
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SBRuleBasedBudgetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SBRuleBasedBudget
        //private SBRuleBasedBudget instance;

        public SBRuleBasedBudgetTests()
        {
            // TODO uncomment below to create an instance of SBRuleBasedBudget
            //instance = new SBRuleBasedBudget();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SBRuleBasedBudget
        /// </summary>
        [Fact]
        public void SBRuleBasedBudgetInstanceTest()
        {
            // TODO uncomment below to test "IsType" SBRuleBasedBudget
            //Assert.IsType<SBRuleBasedBudget>(instance);
        }


        /// <summary>
        /// Test the property 'ExecutionTime'
        /// </summary>
        [Fact]
        public void ExecutionTimeTest()
        {
            // TODO unit test for the property 'ExecutionTime'
        }
        /// <summary>
        /// Test the property 'AppliedRule'
        /// </summary>
        [Fact]
        public void AppliedRuleTest()
        {
            // TODO unit test for the property 'AppliedRule'
        }
        /// <summary>
        /// Test the property 'RuleBasedBudgetValue'
        /// </summary>
        [Fact]
        public void RuleBasedBudgetValueTest()
        {
            // TODO unit test for the property 'RuleBasedBudgetValue'
        }
        /// <summary>
        /// Test the property 'DailyBudgetValue'
        /// </summary>
        [Fact]
        public void DailyBudgetValueTest()
        {
            // TODO unit test for the property 'DailyBudgetValue'
        }
        /// <summary>
        /// Test the property 'PerformanceMetric'
        /// </summary>
        [Fact]
        public void PerformanceMetricTest()
        {
            // TODO unit test for the property 'PerformanceMetric'
        }

    }

}
