/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsInternalErrorErrorCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsInternalErrorErrorCodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsInternalErrorErrorCode
        //private SponsoredProductsInternalErrorErrorCode instance;

        public SponsoredProductsInternalErrorErrorCodeTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsInternalErrorErrorCode
            //instance = new SponsoredProductsInternalErrorErrorCode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsInternalErrorErrorCode
        /// </summary>
        [Fact]
        public void SponsoredProductsInternalErrorErrorCodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsInternalErrorErrorCode
            //Assert.IsType<SponsoredProductsInternalErrorErrorCode>(instance);
        }



    }

}
