/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent
        //private SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent instance;

        public SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent
            //instance = new SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent
        /// </summary>
        [Fact]
        public void SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent
            //Assert.IsType<SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent>(instance);
        }


        /// <summary>
        /// Test the property 'DraftProductAds'
        /// </summary>
        [Fact]
        public void DraftProductAdsTest()
        {
            // TODO unit test for the property 'DraftProductAds'
        }

    }

}
