/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsMarketplaceState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsMarketplaceStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsMarketplaceState
        //private SponsoredProductsMarketplaceState instance;

        public SponsoredProductsMarketplaceStateTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsMarketplaceState
            //instance = new SponsoredProductsMarketplaceState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsMarketplaceState
        /// </summary>
        [Fact]
        public void SponsoredProductsMarketplaceStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsMarketplaceState
            //Assert.IsType<SponsoredProductsMarketplaceState>(instance);
        }


        /// <summary>
        /// Test the property 'Marketplace'
        /// </summary>
        [Fact]
        public void MarketplaceTest()
        {
            // TODO unit test for the property 'Marketplace'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

    }

}
