/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem
        //private SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem instance;

        public SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItemTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem
            //instance = new SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem
        /// </summary>
        [Fact]
        public void SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem
            //Assert.IsType<SponsoredProductsDraftNegativeTargetingClauseSuccessResponseItem>(instance);
        }


        /// <summary>
        /// Test the property 'TargetId'
        /// </summary>
        [Fact]
        public void TargetIdTest()
        {
            // TODO unit test for the property 'TargetId'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'NegativeTargetingClause'
        /// </summary>
        [Fact]
        public void NegativeTargetingClauseTest()
        {
            // TODO unit test for the property 'NegativeTargetingClause'
        }

    }

}
