/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsUpdateNegativeTargetingClause
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsUpdateNegativeTargetingClauseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsUpdateNegativeTargetingClause
        //private SponsoredProductsUpdateNegativeTargetingClause instance;

        public SponsoredProductsUpdateNegativeTargetingClauseTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsUpdateNegativeTargetingClause
            //instance = new SponsoredProductsUpdateNegativeTargetingClause();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsUpdateNegativeTargetingClause
        /// </summary>
        [Fact]
        public void SponsoredProductsUpdateNegativeTargetingClauseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsUpdateNegativeTargetingClause
            //Assert.IsType<SponsoredProductsUpdateNegativeTargetingClause>(instance);
        }


        /// <summary>
        /// Test the property 'Expression'
        /// </summary>
        [Fact]
        public void ExpressionTest()
        {
            // TODO unit test for the property 'Expression'
        }
        /// <summary>
        /// Test the property 'TargetId'
        /// </summary>
        [Fact]
        public void TargetIdTest()
        {
            // TODO unit test for the property 'TargetId'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

    }

}
