/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent
        //private SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent instance;

        public SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent
            //instance = new SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent
        /// </summary>
        [Fact]
        public void SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent
            //Assert.IsType<SponsoredProductsCreateSponsoredProductsGlobalKeywordsResponseContent>(instance);
        }


        /// <summary>
        /// Test the property 'Keywords'
        /// </summary>
        [Fact]
        public void KeywordsTest()
        {
            // TODO unit test for the property 'Keywords'
        }

    }

}
