/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsCreateOrUpdateDraftCampaignDynamicBidding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsCreateOrUpdateDraftCampaignDynamicBiddingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsCreateOrUpdateDraftCampaignDynamicBidding
        //private SponsoredProductsCreateOrUpdateDraftCampaignDynamicBidding instance;

        public SponsoredProductsCreateOrUpdateDraftCampaignDynamicBiddingTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsCreateOrUpdateDraftCampaignDynamicBidding
            //instance = new SponsoredProductsCreateOrUpdateDraftCampaignDynamicBidding();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsCreateOrUpdateDraftCampaignDynamicBidding
        /// </summary>
        [Fact]
        public void SponsoredProductsCreateOrUpdateDraftCampaignDynamicBiddingInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsCreateOrUpdateDraftCampaignDynamicBidding
            //Assert.IsType<SponsoredProductsCreateOrUpdateDraftCampaignDynamicBidding>(instance);
        }


        /// <summary>
        /// Test the property 'PlacementBidding'
        /// </summary>
        [Fact]
        public void PlacementBiddingTest()
        {
            // TODO unit test for the property 'PlacementBidding'
        }
        /// <summary>
        /// Test the property 'Strategy'
        /// </summary>
        [Fact]
        public void StrategyTest()
        {
            // TODO unit test for the property 'Strategy'
        }

    }

}
