/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsGlobalNegativeKeywordSuccessResponseItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsGlobalNegativeKeywordSuccessResponseItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsGlobalNegativeKeywordSuccessResponseItem
        //private SponsoredProductsGlobalNegativeKeywordSuccessResponseItem instance;

        public SponsoredProductsGlobalNegativeKeywordSuccessResponseItemTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsGlobalNegativeKeywordSuccessResponseItem
            //instance = new SponsoredProductsGlobalNegativeKeywordSuccessResponseItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsGlobalNegativeKeywordSuccessResponseItem
        /// </summary>
        [Fact]
        public void SponsoredProductsGlobalNegativeKeywordSuccessResponseItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsGlobalNegativeKeywordSuccessResponseItem
            //Assert.IsType<SponsoredProductsGlobalNegativeKeywordSuccessResponseItem>(instance);
        }


        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'NegativeKeyword'
        /// </summary>
        [Fact]
        public void NegativeKeywordTest()
        {
            // TODO unit test for the property 'NegativeKeyword'
        }
        /// <summary>
        /// Test the property 'NegativeKeywordId'
        /// </summary>
        [Fact]
        public void NegativeKeywordIdTest()
        {
            // TODO unit test for the property 'NegativeKeywordId'
        }

    }

}
