/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsGlobalProductAd
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsGlobalProductAdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsGlobalProductAd
        //private SponsoredProductsGlobalProductAd instance;

        public SponsoredProductsGlobalProductAdTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsGlobalProductAd
            //instance = new SponsoredProductsGlobalProductAd();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsGlobalProductAd
        /// </summary>
        [Fact]
        public void SponsoredProductsGlobalProductAdInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsGlobalProductAd
            //Assert.IsType<SponsoredProductsGlobalProductAd>(instance);
        }


        /// <summary>
        /// Test the property 'AdId'
        /// </summary>
        [Fact]
        public void AdIdTest()
        {
            // TODO unit test for the property 'AdId'
        }
        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            // TODO unit test for the property 'CampaignId'
        }
        /// <summary>
        /// Test the property 'CustomText'
        /// </summary>
        [Fact]
        public void CustomTextTest()
        {
            // TODO unit test for the property 'CustomText'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Asin'
        /// </summary>
        [Fact]
        public void AsinTest()
        {
            // TODO unit test for the property 'Asin'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Fact]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'AdGroupId'
        /// </summary>
        [Fact]
        public void AdGroupIdTest()
        {
            // TODO unit test for the property 'AdGroupId'
        }
        /// <summary>
        /// Test the property 'ExtendedData'
        /// </summary>
        [Fact]
        public void ExtendedDataTest()
        {
            // TODO unit test for the property 'ExtendedData'
        }

    }

}
