/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsListSponsoredProductsDraftKeywordsRequestContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsListSponsoredProductsDraftKeywordsRequestContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsListSponsoredProductsDraftKeywordsRequestContent
        //private SponsoredProductsListSponsoredProductsDraftKeywordsRequestContent instance;

        public SponsoredProductsListSponsoredProductsDraftKeywordsRequestContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsListSponsoredProductsDraftKeywordsRequestContent
            //instance = new SponsoredProductsListSponsoredProductsDraftKeywordsRequestContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsListSponsoredProductsDraftKeywordsRequestContent
        /// </summary>
        [Fact]
        public void SponsoredProductsListSponsoredProductsDraftKeywordsRequestContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsListSponsoredProductsDraftKeywordsRequestContent
            //Assert.IsType<SponsoredProductsListSponsoredProductsDraftKeywordsRequestContent>(instance);
        }


        /// <summary>
        /// Test the property 'CampaignIdFilter'
        /// </summary>
        [Fact]
        public void CampaignIdFilterTest()
        {
            // TODO unit test for the property 'CampaignIdFilter'
        }
        /// <summary>
        /// Test the property 'MaxResults'
        /// </summary>
        [Fact]
        public void MaxResultsTest()
        {
            // TODO unit test for the property 'MaxResults'
        }
        /// <summary>
        /// Test the property 'NextToken'
        /// </summary>
        [Fact]
        public void NextTokenTest()
        {
            // TODO unit test for the property 'NextToken'
        }
        /// <summary>
        /// Test the property 'AdGroupIdFilter'
        /// </summary>
        [Fact]
        public void AdGroupIdFilterTest()
        {
            // TODO unit test for the property 'AdGroupIdFilter'
        }
        /// <summary>
        /// Test the property 'IncludeExtendedDataFields'
        /// </summary>
        [Fact]
        public void IncludeExtendedDataFieldsTest()
        {
            // TODO unit test for the property 'IncludeExtendedDataFields'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
        /// <summary>
        /// Test the property 'KeywordTextFilter'
        /// </summary>
        [Fact]
        public void KeywordTextFilterTest()
        {
            // TODO unit test for the property 'KeywordTextFilter'
        }
        /// <summary>
        /// Test the property 'KeywordIdFilter'
        /// </summary>
        [Fact]
        public void KeywordIdFilterTest()
        {
            // TODO unit test for the property 'KeywordIdFilter'
        }
        /// <summary>
        /// Test the property 'MatchTypeFilter'
        /// </summary>
        [Fact]
        public void MatchTypeFilterTest()
        {
            // TODO unit test for the property 'MatchTypeFilter'
        }

    }

}
