/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent
        //private SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent instance;

        public SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent
            //instance = new SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent
        /// </summary>
        [Fact]
        public void SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent
            //Assert.IsType<SponsoredProductsDeleteSponsoredProductsDraftNegativeTargetingClausesResponseContent>(instance);
        }


        /// <summary>
        /// Test the property 'NegativeTargetingClauses'
        /// </summary>
        [Fact]
        public void NegativeTargetingClausesTest()
        {
            // TODO unit test for the property 'NegativeTargetingClauses'
        }

    }

}
