/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContent
        //private SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContent instance;

        public SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContent
            //instance = new SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContent
        /// </summary>
        [Fact]
        public void SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContent
            //Assert.IsType<SponsoredProductsDeleteSponsoredProductsCampaignNegativeTargetingClausesResponseContent>(instance);
        }


        /// <summary>
        /// Test the property 'CampaignNegativeTargetingClauses'
        /// </summary>
        [Fact]
        public void CampaignNegativeTargetingClausesTest()
        {
            // TODO unit test for the property 'CampaignNegativeTargetingClauses'
        }

    }

}
