/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsBulkGlobalProductAdOperationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsBulkGlobalProductAdOperationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsBulkGlobalProductAdOperationResponse
        //private SponsoredProductsBulkGlobalProductAdOperationResponse instance;

        public SponsoredProductsBulkGlobalProductAdOperationResponseTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsBulkGlobalProductAdOperationResponse
            //instance = new SponsoredProductsBulkGlobalProductAdOperationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsBulkGlobalProductAdOperationResponse
        /// </summary>
        [Fact]
        public void SponsoredProductsBulkGlobalProductAdOperationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsBulkGlobalProductAdOperationResponse
            //Assert.IsType<SponsoredProductsBulkGlobalProductAdOperationResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

    }

}
