/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent
        //private SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent instance;

        public SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent
            //instance = new SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent
        /// </summary>
        [Fact]
        public void SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent
            //Assert.IsType<SponsoredProductsCreateSponsoredProductsDraftAdGroupsRequestContent>(instance);
        }


        /// <summary>
        /// Test the property 'AdGroups'
        /// </summary>
        [Fact]
        public void AdGroupsTest()
        {
            // TODO unit test for the property 'AdGroups'
        }

    }

}
