/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContent
        //private SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContent instance;

        public SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContent
            //instance = new SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContent
        /// </summary>
        [Fact]
        public void SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContent
            //Assert.IsType<SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewRequestContent>(instance);
        }


        /// <summary>
        /// Test the property 'CampaignIdFilter'
        /// </summary>
        [Fact]
        public void CampaignIdFilterTest()
        {
            // TODO unit test for the property 'CampaignIdFilter'
        }
        /// <summary>
        /// Test the property 'StateFilter'
        /// </summary>
        [Fact]
        public void StateFilterTest()
        {
            // TODO unit test for the property 'StateFilter'
        }
        /// <summary>
        /// Test the property 'NegativeKeywordTextFilter'
        /// </summary>
        [Fact]
        public void NegativeKeywordTextFilterTest()
        {
            // TODO unit test for the property 'NegativeKeywordTextFilter'
        }
        /// <summary>
        /// Test the property 'MaxResults'
        /// </summary>
        [Fact]
        public void MaxResultsTest()
        {
            // TODO unit test for the property 'MaxResults'
        }
        /// <summary>
        /// Test the property 'NextToken'
        /// </summary>
        [Fact]
        public void NextTokenTest()
        {
            // TODO unit test for the property 'NextToken'
        }
        /// <summary>
        /// Test the property 'AdGroupIdFilter'
        /// </summary>
        [Fact]
        public void AdGroupIdFilterTest()
        {
            // TODO unit test for the property 'AdGroupIdFilter'
        }
        /// <summary>
        /// Test the property 'IncludeExtendedDataFields'
        /// </summary>
        [Fact]
        public void IncludeExtendedDataFieldsTest()
        {
            // TODO unit test for the property 'IncludeExtendedDataFields'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
        /// <summary>
        /// Test the property 'NegativeKeywordIdFilter'
        /// </summary>
        [Fact]
        public void NegativeKeywordIdFilterTest()
        {
            // TODO unit test for the property 'NegativeKeywordIdFilter'
        }
        /// <summary>
        /// Test the property 'MatchTypeFilter'
        /// </summary>
        [Fact]
        public void MatchTypeFilterTest()
        {
            // TODO unit test for the property 'MatchTypeFilter'
        }

    }

}
