/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsKeywordServingStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsKeywordServingStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsKeywordServingStatus
        //private SponsoredProductsKeywordServingStatus instance;

        public SponsoredProductsKeywordServingStatusTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsKeywordServingStatus
            //instance = new SponsoredProductsKeywordServingStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsKeywordServingStatus
        /// </summary>
        [Fact]
        public void SponsoredProductsKeywordServingStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsKeywordServingStatus
            //Assert.IsType<SponsoredProductsKeywordServingStatus>(instance);
        }



    }

}
