/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsUpdateGlobalTargetingClause
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsUpdateGlobalTargetingClauseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsUpdateGlobalTargetingClause
        //private SponsoredProductsUpdateGlobalTargetingClause instance;

        public SponsoredProductsUpdateGlobalTargetingClauseTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsUpdateGlobalTargetingClause
            //instance = new SponsoredProductsUpdateGlobalTargetingClause();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsUpdateGlobalTargetingClause
        /// </summary>
        [Fact]
        public void SponsoredProductsUpdateGlobalTargetingClauseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsUpdateGlobalTargetingClause
            //Assert.IsType<SponsoredProductsUpdateGlobalTargetingClause>(instance);
        }


        /// <summary>
        /// Test the property 'Expression'
        /// </summary>
        [Fact]
        public void ExpressionTest()
        {
            // TODO unit test for the property 'Expression'
        }
        /// <summary>
        /// Test the property 'TargetId'
        /// </summary>
        [Fact]
        public void TargetIdTest()
        {
            // TODO unit test for the property 'TargetId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ExpressionType'
        /// </summary>
        [Fact]
        public void ExpressionTypeTest()
        {
            // TODO unit test for the property 'ExpressionType'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Bid'
        /// </summary>
        [Fact]
        public void BidTest()
        {
            // TODO unit test for the property 'Bid'
        }

    }

}
