/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContent
        //private SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContent instance;

        public SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContent
            //instance = new SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContent
        /// </summary>
        [Fact]
        public void SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContent
            //Assert.IsType<SponsoredProductsListSponsoredProductsNegativeKeywordsPreviewResponseContent>(instance);
        }


        /// <summary>
        /// Test the property 'NegativeKeywords'
        /// </summary>
        [Fact]
        public void NegativeKeywordsTest()
        {
            // TODO unit test for the property 'NegativeKeywords'
        }
        /// <summary>
        /// Test the property 'TotalResults'
        /// </summary>
        [Fact]
        public void TotalResultsTest()
        {
            // TODO unit test for the property 'TotalResults'
        }
        /// <summary>
        /// Test the property 'NextToken'
        /// </summary>
        [Fact]
        public void NextTokenTest()
        {
            // TODO unit test for the property 'NextToken'
        }

    }

}
