/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContent
        //private SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContent instance;

        public SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContent
            //instance = new SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContent
        /// </summary>
        [Fact]
        public void SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContent
            //Assert.IsType<SponsoredProductsListSponsoredProductsGlobalKeywordsRequestContent>(instance);
        }


        /// <summary>
        /// Test the property 'MaxResults'
        /// </summary>
        [Fact]
        public void MaxResultsTest()
        {
            // TODO unit test for the property 'MaxResults'
        }
        /// <summary>
        /// Test the property 'NextToken'
        /// </summary>
        [Fact]
        public void NextTokenTest()
        {
            // TODO unit test for the property 'NextToken'
        }
        /// <summary>
        /// Test the property 'IncludeExtendedDataFields'
        /// </summary>
        [Fact]
        public void IncludeExtendedDataFieldsTest()
        {
            // TODO unit test for the property 'IncludeExtendedDataFields'
        }
        /// <summary>
        /// Test the property 'KeywordIdFilter'
        /// </summary>
        [Fact]
        public void KeywordIdFilterTest()
        {
            // TODO unit test for the property 'KeywordIdFilter'
        }

    }

}
