/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsKeywordAccessExceptionResponseContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsKeywordAccessExceptionResponseContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsKeywordAccessExceptionResponseContent
        //private SponsoredProductsKeywordAccessExceptionResponseContent instance;

        public SponsoredProductsKeywordAccessExceptionResponseContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsKeywordAccessExceptionResponseContent
            //instance = new SponsoredProductsKeywordAccessExceptionResponseContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsKeywordAccessExceptionResponseContent
        /// </summary>
        [Fact]
        public void SponsoredProductsKeywordAccessExceptionResponseContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsKeywordAccessExceptionResponseContent
            //Assert.IsType<SponsoredProductsKeywordAccessExceptionResponseContent>(instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
