/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContent
        //private SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContent instance;

        public SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContent
            //instance = new SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContent
        /// </summary>
        [Fact]
        public void SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContent
            //Assert.IsType<SponsoredProductsListSponsoredProductsDraftAdGroupsRequestContent>(instance);
        }


        /// <summary>
        /// Test the property 'CampaignIdFilter'
        /// </summary>
        [Fact]
        public void CampaignIdFilterTest()
        {
            // TODO unit test for the property 'CampaignIdFilter'
        }
        /// <summary>
        /// Test the property 'MaxResults'
        /// </summary>
        [Fact]
        public void MaxResultsTest()
        {
            // TODO unit test for the property 'MaxResults'
        }
        /// <summary>
        /// Test the property 'NextToken'
        /// </summary>
        [Fact]
        public void NextTokenTest()
        {
            // TODO unit test for the property 'NextToken'
        }
        /// <summary>
        /// Test the property 'AdGroupIdFilter'
        /// </summary>
        [Fact]
        public void AdGroupIdFilterTest()
        {
            // TODO unit test for the property 'AdGroupIdFilter'
        }
        /// <summary>
        /// Test the property 'IncludeExtendedDataFields'
        /// </summary>
        [Fact]
        public void IncludeExtendedDataFieldsTest()
        {
            // TODO unit test for the property 'IncludeExtendedDataFields'
        }
        /// <summary>
        /// Test the property 'NameFilter'
        /// </summary>
        [Fact]
        public void NameFilterTest()
        {
            // TODO unit test for the property 'NameFilter'
        }
        /// <summary>
        /// Test the property 'CampaignTargetingTypeFilter'
        /// </summary>
        [Fact]
        public void CampaignTargetingTypeFilterTest()
        {
            // TODO unit test for the property 'CampaignTargetingTypeFilter'
        }

    }

}
