/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsDraftTargetMutationErrorSelector
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsDraftTargetMutationErrorSelectorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsDraftTargetMutationErrorSelector
        //private SponsoredProductsDraftTargetMutationErrorSelector instance;

        public SponsoredProductsDraftTargetMutationErrorSelectorTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsDraftTargetMutationErrorSelector
            //instance = new SponsoredProductsDraftTargetMutationErrorSelector();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsDraftTargetMutationErrorSelector
        /// </summary>
        [Fact]
        public void SponsoredProductsDraftTargetMutationErrorSelectorInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsDraftTargetMutationErrorSelector
            //Assert.IsType<SponsoredProductsDraftTargetMutationErrorSelector>(instance);
        }


        /// <summary>
        /// Test the property 'EntityNotFoundError'
        /// </summary>
        [Fact]
        public void EntityNotFoundErrorTest()
        {
            // TODO unit test for the property 'EntityNotFoundError'
        }
        /// <summary>
        /// Test the property 'EntityStateError'
        /// </summary>
        [Fact]
        public void EntityStateErrorTest()
        {
            // TODO unit test for the property 'EntityStateError'
        }
        /// <summary>
        /// Test the property 'MissingValueError'
        /// </summary>
        [Fact]
        public void MissingValueErrorTest()
        {
            // TODO unit test for the property 'MissingValueError'
        }
        /// <summary>
        /// Test the property 'BiddingError'
        /// </summary>
        [Fact]
        public void BiddingErrorTest()
        {
            // TODO unit test for the property 'BiddingError'
        }
        /// <summary>
        /// Test the property 'MalformedValueError'
        /// </summary>
        [Fact]
        public void MalformedValueErrorTest()
        {
            // TODO unit test for the property 'MalformedValueError'
        }
        /// <summary>
        /// Test the property 'DuplicateValueError'
        /// </summary>
        [Fact]
        public void DuplicateValueErrorTest()
        {
            // TODO unit test for the property 'DuplicateValueError'
        }
        /// <summary>
        /// Test the property 'BillingError'
        /// </summary>
        [Fact]
        public void BillingErrorTest()
        {
            // TODO unit test for the property 'BillingError'
        }
        /// <summary>
        /// Test the property 'EntityQuotaError'
        /// </summary>
        [Fact]
        public void EntityQuotaErrorTest()
        {
            // TODO unit test for the property 'EntityQuotaError'
        }
        /// <summary>
        /// Test the property 'InternalServerError'
        /// </summary>
        [Fact]
        public void InternalServerErrorTest()
        {
            // TODO unit test for the property 'InternalServerError'
        }
        /// <summary>
        /// Test the property 'RangeError'
        /// </summary>
        [Fact]
        public void RangeErrorTest()
        {
            // TODO unit test for the property 'RangeError'
        }
        /// <summary>
        /// Test the property 'OtherError'
        /// </summary>
        [Fact]
        public void OtherErrorTest()
        {
            // TODO unit test for the property 'OtherError'
        }
        /// <summary>
        /// Test the property 'ThrottledError'
        /// </summary>
        [Fact]
        public void ThrottledErrorTest()
        {
            // TODO unit test for the property 'ThrottledError'
        }

    }

}
