/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem
        //private SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem instance;

        public SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItemTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem
            //instance = new SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem
        /// </summary>
        [Fact]
        public void SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem
            //Assert.IsType<SponsoredProductsCampaignNegativeTargetingClauseSuccessResponseItem>(instance);
        }


        /// <summary>
        /// Test the property 'CampaignNegativeTargetingClauseId'
        /// </summary>
        [Fact]
        public void CampaignNegativeTargetingClauseIdTest()
        {
            // TODO unit test for the property 'CampaignNegativeTargetingClauseId'
        }
        /// <summary>
        /// Test the property 'CampaignNegativeTargetingClauses'
        /// </summary>
        [Fact]
        public void CampaignNegativeTargetingClausesTest()
        {
            // TODO unit test for the property 'CampaignNegativeTargetingClauses'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

    }

}
