/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsGlobalProductAServingStatusReason
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsGlobalProductAServingStatusReasonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsGlobalProductAServingStatusReason
        //private SponsoredProductsGlobalProductAServingStatusReason instance;

        public SponsoredProductsGlobalProductAServingStatusReasonTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsGlobalProductAServingStatusReason
            //instance = new SponsoredProductsGlobalProductAServingStatusReason();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsGlobalProductAServingStatusReason
        /// </summary>
        [Fact]
        public void SponsoredProductsGlobalProductAServingStatusReasonInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsGlobalProductAServingStatusReason
            //Assert.IsType<SponsoredProductsGlobalProductAServingStatusReason>(instance);
        }



    }

}
