/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContent
        //private SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContent instance;

        public SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContentTests()
        {
            // TODO uncomment below to create an instance of SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContent
            //instance = new SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContent
        /// </summary>
        [Fact]
        public void SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContent
            //Assert.IsType<SponsoredProductsListSponsoredProductsGlobalNegativeKeywordsRequestContent>(instance);
        }


        /// <summary>
        /// Test the property 'MaxResults'
        /// </summary>
        [Fact]
        public void MaxResultsTest()
        {
            // TODO unit test for the property 'MaxResults'
        }
        /// <summary>
        /// Test the property 'NextToken'
        /// </summary>
        [Fact]
        public void NextTokenTest()
        {
            // TODO unit test for the property 'NextToken'
        }
        /// <summary>
        /// Test the property 'IncludeExtendedDataFields'
        /// </summary>
        [Fact]
        public void IncludeExtendedDataFieldsTest()
        {
            // TODO unit test for the property 'IncludeExtendedDataFields'
        }
        /// <summary>
        /// Test the property 'NegativeKeywordIdFilter'
        /// </summary>
        [Fact]
        public void NegativeKeywordIdFilterTest()
        {
            // TODO unit test for the property 'NegativeKeywordIdFilter'
        }

    }

}
