/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;
using Amazon.Advertising.SponsoredProducts.Model;

using Newtonsoft.Json;

using Xunit;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing TargetingGroupBidRecommendation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TargetingGroupBidRecommendationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TargetingGroupBidRecommendation
        //private TargetingGroupBidRecommendation instance;

        public TargetingGroupBidRecommendationTests()
        {
            // TODO uncomment below to create an instance of TargetingGroupBidRecommendation
            //instance = new TargetingGroupBidRecommendation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TargetingGroupBidRecommendation
        /// </summary>
        [Fact]
        public void TargetingGroupBidRecommendationInstanceTest()
        {
            // TODO uncomment below to test "IsType" TargetingGroupBidRecommendation
            //Assert.IsType<TargetingGroupBidRecommendation>(instance);
        }


        /// <summary>
        /// Test the property 'SuggestedBid'
        /// </summary>
        [Fact]
        public void SuggestedBidTest()
        {
            // TODO unit test for the property 'SuggestedBid'
        }
        /// <summary>
        /// Test the property 'TargetId'
        /// </summary>
        [Fact]
        public void TargetIdTest()
        {
            // TODO unit test for the property 'TargetId'
        }
        /// <summary>
        /// Test the property 'TargetingGroupExpression'
        /// </summary>
        [Fact]
        public void TargetingGroupExpressionTest()
        {
            // TODO unit test for the property 'TargetingGroupExpression'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'AdGroupId'
        /// </summary>
        [Fact]
        public void AdGroupIdTest()
        {
            // TODO unit test for the property 'AdGroupId'
        }

    }

}
