/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Model;
using Amazon.Advertising.SponsoredProducts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.Advertising.SponsoredProducts.Test.Model
{
    /// <summary>
    ///  Class for testing ThemeBasedBidRecommendationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThemeBasedBidRecommendationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ThemeBasedBidRecommendationResponse
        //private ThemeBasedBidRecommendationResponse instance;

        public ThemeBasedBidRecommendationResponseTests()
        {
            // TODO uncomment below to create an instance of ThemeBasedBidRecommendationResponse
            //instance = new ThemeBasedBidRecommendationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ThemeBasedBidRecommendationResponse
        /// </summary>
        [Fact]
        public void ThemeBasedBidRecommendationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ThemeBasedBidRecommendationResponse
            //Assert.IsType<ThemeBasedBidRecommendationResponse>(instance);
        }


        /// <summary>
        /// Test the property 'BidRecommendations'
        /// </summary>
        [Fact]
        public void BidRecommendationsTest()
        {
            // TODO unit test for the property 'BidRecommendations'
        }

    }

}
