/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

using OpenAPIDateConverter = Amazon.Advertising.SponsoredProducts.Client.OpenAPIDateConverter;

namespace Amazon.Advertising.SponsoredProducts.Model
{
    /// <summary>
    /// The comparison operator.
    /// </summary>
    /// <value>The comparison operator.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ComparisonOperator
    {
        /// <summary>
        /// Enum GREATERTHAN for value: GREATER_THAN
        /// </summary>
        [EnumMember(Value = "GREATER_THAN")]
        GREATERTHAN = 1,

        /// <summary>
        /// Enum LESSTHAN for value: LESS_THAN
        /// </summary>
        [EnumMember(Value = "LESS_THAN")]
        LESSTHAN = 2,

        /// <summary>
        /// Enum EQUALTO for value: EQUAL_TO
        /// </summary>
        [EnumMember(Value = "EQUAL_TO")]
        EQUALTO = 3,

        /// <summary>
        /// Enum LESSTHANOREQUALTO for value: LESS_THAN_OR_EQUAL_TO
        /// </summary>
        [EnumMember(Value = "LESS_THAN_OR_EQUAL_TO")]
        LESSTHANOREQUALTO = 4,

        /// <summary>
        /// Enum GREATERTHANOREQUALTO for value: GREATER_THAN_OR_EQUAL_TO
        /// </summary>
        [EnumMember(Value = "GREATER_THAN_OR_EQUAL_TO")]
        GREATERTHANOREQUALTO = 5

    }

}
