/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Amazon.Advertising.SponsoredProducts.Client.OpenAPIDateConverter;

namespace Amazon.Advertising.SponsoredProducts.Model
{
    /// <summary>
    /// SBRuleDuration
    /// </summary>
    [DataContract(Name = "SBRuleDuration")]
    public partial class SBRuleDuration : IEquatable<SBRuleDuration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SBRuleDuration" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SBRuleDuration() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SBRuleDuration" /> class.
        /// </summary>
        /// <param name="dateRangeTypeRuleDuration">dateRangeTypeRuleDuration (required).</param>
        public SBRuleDuration(DateRangeTypeRuleDuration dateRangeTypeRuleDuration = default(DateRangeTypeRuleDuration))
        {
            // to ensure "dateRangeTypeRuleDuration" is required (not null)
            if (dateRangeTypeRuleDuration == null)
            {
                throw new ArgumentNullException("dateRangeTypeRuleDuration is a required property for SBRuleDuration and cannot be null");
            }
            this.DateRangeTypeRuleDuration = dateRangeTypeRuleDuration;
        }

        /// <summary>
        /// Gets or Sets DateRangeTypeRuleDuration
        /// </summary>
        [DataMember(Name = "dateRangeTypeRuleDuration", IsRequired = true, EmitDefaultValue = true)]
        public DateRangeTypeRuleDuration DateRangeTypeRuleDuration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SBRuleDuration {\n");
            sb.Append("  DateRangeTypeRuleDuration: ").Append(DateRangeTypeRuleDuration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SBRuleDuration);
        }

        /// <summary>
        /// Returns true if SBRuleDuration instances are equal
        /// </summary>
        /// <param name="input">Instance of SBRuleDuration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SBRuleDuration input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DateRangeTypeRuleDuration == input.DateRangeTypeRuleDuration ||
                    (this.DateRangeTypeRuleDuration != null &&
                    this.DateRangeTypeRuleDuration.Equals(input.DateRangeTypeRuleDuration))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DateRangeTypeRuleDuration != null)
                {
                    hashCode = (hashCode * 59) + this.DateRangeTypeRuleDuration.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
