/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Amazon.Advertising.SponsoredProducts.Client.OpenAPIDateConverter;

namespace Amazon.Advertising.SponsoredProducts.Model
{
    /// <summary>
    /// SPCampaignOptimizationRecommendationsAPIRequest
    /// </summary>
    [DataContract(Name = "SPCampaignOptimizationRecommendationsAPIRequest")]
    public partial class SPCampaignOptimizationRecommendationsAPIRequest : IEquatable<SPCampaignOptimizationRecommendationsAPIRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SPCampaignOptimizationRecommendationsAPIRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SPCampaignOptimizationRecommendationsAPIRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SPCampaignOptimizationRecommendationsAPIRequest" /> class.
        /// </summary>
        /// <param name="campaignIds">A list of campaign ids (required).</param>
        public SPCampaignOptimizationRecommendationsAPIRequest(List<string> campaignIds = default(List<string>))
        {
            // to ensure "campaignIds" is required (not null)
            if (campaignIds == null)
            {
                throw new ArgumentNullException("campaignIds is a required property for SPCampaignOptimizationRecommendationsAPIRequest and cannot be null");
            }
            this.CampaignIds = campaignIds;
        }

        /// <summary>
        /// A list of campaign ids
        /// </summary>
        /// <value>A list of campaign ids</value>
        [DataMember(Name = "campaignIds", IsRequired = true, EmitDefaultValue = true)]
        public List<string> CampaignIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SPCampaignOptimizationRecommendationsAPIRequest {\n");
            sb.Append("  CampaignIds: ").Append(CampaignIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SPCampaignOptimizationRecommendationsAPIRequest);
        }

        /// <summary>
        /// Returns true if SPCampaignOptimizationRecommendationsAPIRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SPCampaignOptimizationRecommendationsAPIRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SPCampaignOptimizationRecommendationsAPIRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.CampaignIds == input.CampaignIds ||
                    this.CampaignIds != null &&
                    input.CampaignIds != null &&
                    this.CampaignIds.SequenceEqual(input.CampaignIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CampaignIds != null)
                {
                    hashCode = (hashCode * 59) + this.CampaignIds.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
