/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Amazon.Advertising.SponsoredProducts.Client.OpenAPIDateConverter;

namespace Amazon.Advertising.SponsoredProducts.Model
{
    /// <summary>
    /// SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent
    /// </summary>
    [DataContract(Name = "SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent")]
    public partial class SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent : IEquatable<SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent" /> class.
        /// </summary>
        /// <param name="campaignNegativeKeywordIdFilter">campaignNegativeKeywordIdFilter (required).</param>
        public SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent(SponsoredProductsObjectIdFilter campaignNegativeKeywordIdFilter = default(SponsoredProductsObjectIdFilter))
        {
            // to ensure "campaignNegativeKeywordIdFilter" is required (not null)
            if (campaignNegativeKeywordIdFilter == null)
            {
                throw new ArgumentNullException("campaignNegativeKeywordIdFilter is a required property for SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent and cannot be null");
            }
            this.CampaignNegativeKeywordIdFilter = campaignNegativeKeywordIdFilter;
        }

        /// <summary>
        /// Gets or Sets CampaignNegativeKeywordIdFilter
        /// </summary>
        [DataMember(Name = "campaignNegativeKeywordIdFilter", IsRequired = true, EmitDefaultValue = true)]
        public SponsoredProductsObjectIdFilter CampaignNegativeKeywordIdFilter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent {\n");
            sb.Append("  CampaignNegativeKeywordIdFilter: ").Append(CampaignNegativeKeywordIdFilter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent);
        }

        /// <summary>
        /// Returns true if SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent instances are equal
        /// </summary>
        /// <param name="input">Instance of SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SponsoredProductsDeleteSponsoredProductsCampaignNegativeKeywordsRequestContent input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CampaignNegativeKeywordIdFilter == input.CampaignNegativeKeywordIdFilter ||
                    (this.CampaignNegativeKeywordIdFilter != null &&
                    this.CampaignNegativeKeywordIdFilter.Equals(input.CampaignNegativeKeywordIdFilter))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CampaignNegativeKeywordIdFilter != null)
                {
                    hashCode = (hashCode * 59) + this.CampaignNegativeKeywordIdFilter.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
