/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Amazon.Advertising.SponsoredProducts.Client.OpenAPIDateConverter;

namespace Amazon.Advertising.SponsoredProducts.Model
{
    /// <summary>
    /// SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent
    /// </summary>
    [DataContract(Name = "SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent")]
    public partial class SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent : IEquatable<SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent" /> class.
        /// </summary>
        /// <param name="draftProductAds">draftProductAds (required).</param>
        public SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent(SponsoredProductsBulkDraftProductAdOperationResponse draftProductAds = default(SponsoredProductsBulkDraftProductAdOperationResponse))
        {
            // to ensure "draftProductAds" is required (not null)
            if (draftProductAds == null)
            {
                throw new ArgumentNullException("draftProductAds is a required property for SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent and cannot be null");
            }
            this.DraftProductAds = draftProductAds;
        }

        /// <summary>
        /// Gets or Sets DraftProductAds
        /// </summary>
        [DataMember(Name = "draftProductAds", IsRequired = true, EmitDefaultValue = true)]
        public SponsoredProductsBulkDraftProductAdOperationResponse DraftProductAds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent {\n");
            sb.Append("  DraftProductAds: ").Append(DraftProductAds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent);
        }

        /// <summary>
        /// Returns true if SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent instances are equal
        /// </summary>
        /// <param name="input">Instance of SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SponsoredProductsCreateSponsoredProductsDraftProductAdsResponseContent input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DraftProductAds == input.DraftProductAds ||
                    (this.DraftProductAds != null &&
                    this.DraftProductAds.Equals(input.DraftProductAds))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DraftProductAds != null)
                {
                    hashCode = (hashCode * 59) + this.DraftProductAds.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
