/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

using OpenAPIDateConverter = Amazon.Advertising.SponsoredProducts.Client.OpenAPIDateConverter;

namespace Amazon.Advertising.SponsoredProducts.Model
{
    /// <summary>
    /// SponsoredProductsDraftCampaignPlacementBidding
    /// </summary>
    [DataContract(Name = "SponsoredProductsDraftCampaignPlacementBidding")]
    public partial class SponsoredProductsDraftCampaignPlacementBidding : IEquatable<SponsoredProductsDraftCampaignPlacementBidding>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Placement
        /// </summary>
        [DataMember(Name = "placement", EmitDefaultValue = false)]
        public SponsoredProductsPlacement? Placement { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SponsoredProductsDraftCampaignPlacementBidding" /> class.
        /// </summary>
        /// <param name="percentage">percentage.</param>
        /// <param name="placement">placement.</param>
        public SponsoredProductsDraftCampaignPlacementBidding(int percentage = default(int), SponsoredProductsPlacement? placement = default(SponsoredProductsPlacement?))
        {
            this.Percentage = percentage;
            this.Placement = placement;
        }

        /// <summary>
        /// Gets or Sets Percentage
        /// </summary>
        [DataMember(Name = "percentage", EmitDefaultValue = false)]
        public int Percentage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SponsoredProductsDraftCampaignPlacementBidding {\n");
            sb.Append("  Percentage: ").Append(Percentage).Append("\n");
            sb.Append("  Placement: ").Append(Placement).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SponsoredProductsDraftCampaignPlacementBidding);
        }

        /// <summary>
        /// Returns true if SponsoredProductsDraftCampaignPlacementBidding instances are equal
        /// </summary>
        /// <param name="input">Instance of SponsoredProductsDraftCampaignPlacementBidding to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SponsoredProductsDraftCampaignPlacementBidding input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.Percentage == input.Percentage ||
                    this.Percentage.Equals(input.Percentage)
                ) &&
                (
                    this.Placement == input.Placement ||
                    this.Placement.Equals(input.Placement)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Percentage.GetHashCode();
                hashCode = (hashCode * 59) + this.Placement.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // Percentage (int) maximum
            if (this.Percentage > (int)900)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Percentage, must be a value less than or equal to 900.", new[] { "Percentage" });
            }

            // Percentage (int) minimum
            if (this.Percentage < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Percentage, must be a value greater than or equal to 0.", new[] { "Percentage" });
            }

            yield break;
        }
    }

}
