/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

using OpenAPIDateConverter = Amazon.Advertising.SponsoredProducts.Client.OpenAPIDateConverter;

namespace Amazon.Advertising.SponsoredProducts.Model
{
    /// <summary>
    /// SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent
    /// </summary>
    [DataContract(Name = "SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent")]
    public partial class SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent : IEquatable<SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent" /> class.
        /// </summary>
        /// <param name="campaignNegativeKeywords">campaignNegativeKeywords (required).</param>
        public SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent(List<SponsoredProductsUpdateCampaignNegativeKeyword> campaignNegativeKeywords = default(List<SponsoredProductsUpdateCampaignNegativeKeyword>))
        {
            // to ensure "campaignNegativeKeywords" is required (not null)
            if (campaignNegativeKeywords == null)
            {
                throw new ArgumentNullException("campaignNegativeKeywords is a required property for SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent and cannot be null");
            }
            this.CampaignNegativeKeywords = campaignNegativeKeywords;
        }

        /// <summary>
        /// Gets or Sets CampaignNegativeKeywords
        /// </summary>
        [DataMember(Name = "campaignNegativeKeywords", IsRequired = true, EmitDefaultValue = true)]
        public List<SponsoredProductsUpdateCampaignNegativeKeyword> CampaignNegativeKeywords { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent {\n");
            sb.Append("  CampaignNegativeKeywords: ").Append(CampaignNegativeKeywords).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent);
        }

        /// <summary>
        /// Returns true if SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent instances are equal
        /// </summary>
        /// <param name="input">Instance of SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsRequestContent input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.CampaignNegativeKeywords == input.CampaignNegativeKeywords ||
                    this.CampaignNegativeKeywords != null &&
                    input.CampaignNegativeKeywords != null &&
                    this.CampaignNegativeKeywords.SequenceEqual(input.CampaignNegativeKeywords)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CampaignNegativeKeywords != null)
                {
                    hashCode = (hashCode * 59) + this.CampaignNegativeKeywords.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
