/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

using OpenAPIDateConverter = Amazon.Advertising.SponsoredProducts.Client.OpenAPIDateConverter;

namespace Amazon.Advertising.SponsoredProducts.Model
{
    /// <summary>
    /// Defines SponsoredProductsGlobalAdGroupMarketplaceServingStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SponsoredProductsGlobalAdGroupMarketplaceServingStatus
    {
        /// <summary>
        /// Enum ADGROUPSTATUSENABLED for value: AD_GROUP_STATUS_ENABLED
        /// </summary>
        [EnumMember(Value = "AD_GROUP_STATUS_ENABLED")]
        ADGROUPSTATUSENABLED = 1,

        /// <summary>
        /// Enum ADGROUPPAUSED for value: AD_GROUP_PAUSED
        /// </summary>
        [EnumMember(Value = "AD_GROUP_PAUSED")]
        ADGROUPPAUSED = 2,

        /// <summary>
        /// Enum ADGROUPARCHIVED for value: AD_GROUP_ARCHIVED
        /// </summary>
        [EnumMember(Value = "AD_GROUP_ARCHIVED")]
        ADGROUPARCHIVED = 3,

        /// <summary>
        /// Enum ADGROUPINCOMPLETE for value: AD_GROUP_INCOMPLETE
        /// </summary>
        [EnumMember(Value = "AD_GROUP_INCOMPLETE")]
        ADGROUPINCOMPLETE = 4,

        /// <summary>
        /// Enum ADGROUPPOLICINGPENDINGREVIEW for value: AD_GROUP_POLICING_PENDING_REVIEW
        /// </summary>
        [EnumMember(Value = "AD_GROUP_POLICING_PENDING_REVIEW")]
        ADGROUPPOLICINGPENDINGREVIEW = 5,

        /// <summary>
        /// Enum ADGROUPPOLICINGCREATIVEREJECTED for value: AD_GROUP_POLICING_CREATIVE_REJECTED
        /// </summary>
        [EnumMember(Value = "AD_GROUP_POLICING_CREATIVE_REJECTED")]
        ADGROUPPOLICINGCREATIVEREJECTED = 6,

        /// <summary>
        /// Enum ADGROUPLOWBID for value: AD_GROUP_LOW_BID
        /// </summary>
        [EnumMember(Value = "AD_GROUP_LOW_BID")]
        ADGROUPLOWBID = 7,

        /// <summary>
        /// Enum CAMPAIGNSTATUSENABLED for value: CAMPAIGN_STATUS_ENABLED
        /// </summary>
        [EnumMember(Value = "CAMPAIGN_STATUS_ENABLED")]
        CAMPAIGNSTATUSENABLED = 8,

        /// <summary>
        /// Enum CAMPAIGNPAUSED for value: CAMPAIGN_PAUSED
        /// </summary>
        [EnumMember(Value = "CAMPAIGN_PAUSED")]
        CAMPAIGNPAUSED = 9,

        /// <summary>
        /// Enum CAMPAIGNARCHIVED for value: CAMPAIGN_ARCHIVED
        /// </summary>
        [EnumMember(Value = "CAMPAIGN_ARCHIVED")]
        CAMPAIGNARCHIVED = 10,

        /// <summary>
        /// Enum PENDINGREVIEW for value: PENDING_REVIEW
        /// </summary>
        [EnumMember(Value = "PENDING_REVIEW")]
        PENDINGREVIEW = 11,

        /// <summary>
        /// Enum REJECTED for value: REJECTED
        /// </summary>
        [EnumMember(Value = "REJECTED")]
        REJECTED = 12,

        /// <summary>
        /// Enum PENDINGSTARTDATE for value: PENDING_START_DATE
        /// </summary>
        [EnumMember(Value = "PENDING_START_DATE")]
        PENDINGSTARTDATE = 13,

        /// <summary>
        /// Enum ENDED for value: ENDED
        /// </summary>
        [EnumMember(Value = "ENDED")]
        ENDED = 14,

        /// <summary>
        /// Enum CAMPAIGNOUTOFBUDGET for value: CAMPAIGN_OUT_OF_BUDGET
        /// </summary>
        [EnumMember(Value = "CAMPAIGN_OUT_OF_BUDGET")]
        CAMPAIGNOUTOFBUDGET = 15,

        /// <summary>
        /// Enum CAMPAIGNINCOMPLETE for value: CAMPAIGN_INCOMPLETE
        /// </summary>
        [EnumMember(Value = "CAMPAIGN_INCOMPLETE")]
        CAMPAIGNINCOMPLETE = 16,

        /// <summary>
        /// Enum ADVERTISERPOLICINGSUSPENDED for value: ADVERTISER_POLICING_SUSPENDED
        /// </summary>
        [EnumMember(Value = "ADVERTISER_POLICING_SUSPENDED")]
        ADVERTISERPOLICINGSUSPENDED = 17,

        /// <summary>
        /// Enum ADVERTISERPOLICINGPENDINGREVIEW for value: ADVERTISER_POLICING_PENDING_REVIEW
        /// </summary>
        [EnumMember(Value = "ADVERTISER_POLICING_PENDING_REVIEW")]
        ADVERTISERPOLICINGPENDINGREVIEW = 18,

        /// <summary>
        /// Enum ADVERTISERARCHIVED for value: ADVERTISER_ARCHIVED
        /// </summary>
        [EnumMember(Value = "ADVERTISER_ARCHIVED")]
        ADVERTISERARCHIVED = 19,

        /// <summary>
        /// Enum ADVERTISERPAUSED for value: ADVERTISER_PAUSED
        /// </summary>
        [EnumMember(Value = "ADVERTISER_PAUSED")]
        ADVERTISERPAUSED = 20,

        /// <summary>
        /// Enum ADVERTISERPAYMENTFAILURE for value: ADVERTISER_PAYMENT_FAILURE
        /// </summary>
        [EnumMember(Value = "ADVERTISER_PAYMENT_FAILURE")]
        ADVERTISERPAYMENTFAILURE = 21,

        /// <summary>
        /// Enum ADVERTISERSTATUSENABLED for value: ADVERTISER_STATUS_ENABLED
        /// </summary>
        [EnumMember(Value = "ADVERTISER_STATUS_ENABLED")]
        ADVERTISERSTATUSENABLED = 22

    }

}
