/*
 * Sponsored Products
 *
 *  
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Reflection;

using Amazon.Advertising.SponsoredProducts.Api;
using Amazon.Advertising.SponsoredProducts.Client;

using RestSharp;

using Xunit;
// uncomment below to import models
//using Amazon.Advertising.SponsoredProducts.Model;

namespace Amazon.Advertising.SponsoredProducts.Test.Api
{
    /// <summary>
    ///  Class for testing AdGroupsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AdGroupsApiTests : IDisposable
    {
        private readonly AdGroupsApi instance;

        public AdGroupsApiTests()
        {
            instance = new AdGroupsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdGroupsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AdGroupsApi
            //Assert.IsType<AdGroupsApi>(instance);
        }

        /// <summary>
        /// Test CreateSponsoredProductsAdGroups
        /// </summary>
        [Fact]
        public void CreateSponsoredProductsAdGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string amazonAdvertisingAPIClientId = null;
            //string amazonAdvertisingAPIScope = null;
            //SponsoredProductsCreateSponsoredProductsAdGroupsRequestContent sponsoredProductsCreateSponsoredProductsAdGroupsRequestContent = null;
            //string? prefer = null;
            //var response = instance.CreateSponsoredProductsAdGroups(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsCreateSponsoredProductsAdGroupsRequestContent, prefer);
            //Assert.IsType<SponsoredProductsCreateSponsoredProductsAdGroupsResponseContent>(response);
        }

        /// <summary>
        /// Test DeleteSponsoredProductsAdGroups
        /// </summary>
        [Fact]
        public void DeleteSponsoredProductsAdGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string amazonAdvertisingAPIClientId = null;
            //string amazonAdvertisingAPIScope = null;
            //SponsoredProductsDeleteSponsoredProductsAdGroupsRequestContent sponsoredProductsDeleteSponsoredProductsAdGroupsRequestContent = null;
            //var response = instance.DeleteSponsoredProductsAdGroups(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsDeleteSponsoredProductsAdGroupsRequestContent);
            //Assert.IsType<SponsoredProductsDeleteSponsoredProductsAdGroupsResponseContent>(response);
        }

        /// <summary>
        /// Test ListSponsoredProductsAdGroups
        /// </summary>
        [Fact]
        public void ListSponsoredProductsAdGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string amazonAdvertisingAPIClientId = null;
            //string amazonAdvertisingAPIScope = null;
            //SponsoredProductsListSponsoredProductsAdGroupsRequestContent? sponsoredProductsListSponsoredProductsAdGroupsRequestContent = null;
            //var response = instance.ListSponsoredProductsAdGroups(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsListSponsoredProductsAdGroupsRequestContent);
            //Assert.IsType<SponsoredProductsListSponsoredProductsAdGroupsResponseContent>(response);
        }

        /// <summary>
        /// Test UpdateSponsoredProductsAdGroups
        /// </summary>
        [Fact]
        public void UpdateSponsoredProductsAdGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string amazonAdvertisingAPIClientId = null;
            //string amazonAdvertisingAPIScope = null;
            //SponsoredProductsUpdateSponsoredProductsAdGroupsRequestContent sponsoredProductsUpdateSponsoredProductsAdGroupsRequestContent = null;
            //string? prefer = null;
            //var response = instance.UpdateSponsoredProductsAdGroups(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsUpdateSponsoredProductsAdGroupsRequestContent, prefer);
            //Assert.IsType<SponsoredProductsUpdateSponsoredProductsAdGroupsResponseContent>(response);
        }
    }
}
